### ISSUE TITLE
geoP

### ISSUE THREAD

**Issue by Zepeng-Mu** [Sun-lab/asSeq_pipelines#1]
Hello,

I wonder which script I should look at if I want to try the geoP method?
Thanks so mcuh!

**Comment by yaceya** [comment]
Sorry for not giving a timely response, we implemented this permutation based method with a function getPermP.R in our package https://github.com/Sun-lab/asSeq 
We clearly should document it better and maybe give a function a name better connected to the name we introduced in the paper.
